/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * User Management API
 * API for user registration, authentication, password reset, and token management.
 * OpenAPI spec version: 1.0.0
 */
import type { GetUsers200Data } from "./getUsers200Data";

export type GetUsers200 = {
  data: GetUsers200Data;
  result: boolean;
};
