/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * User Management API
 * API for user registration, authentication, password reset, and token management.
 * OpenAPI spec version: 1.0.0
 */
import type { GetXrayModules200DataItem } from "./getXrayModules200DataItem";

export type GetXrayModules200 = {
  data: GetXrayModules200DataItem[];
  result: boolean;
};
