/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * User Management API
 * API for user registration, authentication, password reset, and token management.
 * OpenAPI spec version: 1.0.0
 */
import type { GetXrayLab200DataItem } from "./getXrayLab200DataItem";

export type GetXrayLab200 = {
  data: GetXrayLab200DataItem[];
  has_next: boolean;
  has_previous: boolean;
  page_count: number;
  page_no: number;
  result: boolean;
};
