/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * User Management API
 * API for user registration, authentication, password reset, and token management.
 * OpenAPI spec version: 1.0.0
 */

export type GetXrayLabParams = {
  module_id?: string;
  title?: string;
  page_no?: number;
  page_size?: number;
};
