/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * User Management API
 * API for user registration, authentication, password reset, and token management.
 * OpenAPI spec version: 1.0.0
 */
import type { PostUsersLogin200Data } from "./postUsersLogin200Data";

export type PostUsersLogin200 = {
  data?: PostUsersLogin200Data;
  result?: boolean;
};
